# Generated by Django 4.2 on 2023-04-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=28, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=256)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('points', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
