# Generated by Django 4.2 on 2023-04-17 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game1', models.CharField(max_length=256)),
                ('game2', models.CharField(max_length=256)),
                ('game3', models.CharField(max_length=256)),
                ('game4', models.CharField(max_length=256)),
                ('game5', models.CharField(max_length=256)),
                ('game6', models.CharField(max_length=256)),
                ('game7', models.CharField(max_length=256)),
                ('game8', models.CharField(max_length=256)),
                ('game9', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
