# Generated by Django 4.2 on 2023-04-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='game1',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='game2',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='game3',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='game4',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='game5',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='game6',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='game7',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='game8',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='game9',
        ),
        migrations.AddField(
            model_name='bet',
            name='order',
            field=models.CharField(default='default', max_length=4096),
            preserve_default=False,
        ),
    ]
